{
 "title": "mongodb-VictoriaLogs慢查询展示面板",
 "tags": [ "hap-monitor" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   { "name": "job", "label": "节点", "query": { "query": "" } },
   { "name": "durationThreshold", "label": "慢查询耗时", "query": "1000" },
   { "name": "attrNs", "label": "库表", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "## 使用说明\n\n### ⚠️ 查询时间范围限制\n- **<span style=\"color:red\">最大查询时间范围为 24h</span>**\n- **<span style=\"color:red\">请勿选择超过 24 小时的时间范围</span>**\n- **<span style=\"color:red\">时间范围越长，加载耗时稍微越长</span>**  \n  （例如：`Last 3 hours`）\n\n### 📊 查询方式建议\n为保证 **趋势清晰** 与 **查询性能稳定**，建议使用以下固定时间窗口或者指定起止时间：\n\n- **<span style=\"color:green\">Last 30minutes</span>**\n- **<span style=\"color:green\">Last 1h</span>**\n- **<span style=\"color:green\">Last 3h</span>**\n- **<span style=\"color:green\">Last 6h</span>**"
   }
  },
  {
   "title": "mongodb日志面板（最新500条）",
   "type": "logs",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "direction": "desc",
     "expr": "job:=\"$job\" durationMillis:>$durationThreshold ns:\"$attrNs\"",
     "maxLines": 500
    }
   ]
  },
  {
   "title": "慢查询次数趋势（按库表分组）",
   "type": "timeseries",
   "description": "按时间桶统计慢查询次数；鼠标悬停显示该时间桶内每个库表(ns)的慢查询次数。总计 表示此时间点慢查询日志总条目",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "job:=\"$job\" durationMillis:>$durationThreshold\r\n| filter ns:~\"^(${attrNs:pipe})$\"\r\n| stats by (_time:$__interval, ns) count() as value_by_ns\r\n"
    },
    {
     "expr": "job:=\"$job\" durationMillis:>$durationThreshold\r\n| filter ns:~\"^(${attrNs:pipe})$\"\r\n| stats by (_time:$__interval) count() as total\r\n"
    }
   ]
  },
  {
   "title": "慢查询明细（最多500条，按耗时客户端排序）",
   "type": "table",
   "description": "sort by durationThreshold (client-side sort). maxLines 已限制，避免1C2G打满。",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "job:=\"$job\" durationMillis:>$durationThreshold ns:\"$attrNs\"",
     "maxLines": 500
    }
   ]
  },
  {
   "title": "慢查询统计（最多500条）",
   "type": "table",
   "description": "24h内统计推荐用这个面板（聚合后排序，资源占用小）。",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "job:=\"$job\" ns:\"$attrNs\" durationMillis:>$durationThreshold\n| stats by (ns) \n    count() as slow_cnt,\n    max(durationMillis) as max_ms,\n    min(durationMillis) as min_ms\n| sort by (slow_cnt) desc",
     "maxLines": 500
    }
   ]
  }
 ]
}